name: driver-insights-api
octopus:
  space: USXpress
  group: driver
tags:
  owner: US Xpress
  team: Luchadores
  purpose: "Exposes REST services for dealing with Driver Insights"
api: 
  service:
    targetPort: 5000
  configVars:
    ASPNETCORE_URLS: "http://0.0.0.0:5000"
    AWS_REGION: "#{AWS_REGION}"
    API_BASE_PATH: "#{API_BASE_PATH}"
    Sql__psa: "#{SQL_PSA_CONNECTION_STRING}"
    DriverRepository__ConnectionString: "#{MONGO}"
    AttritionApi__Url: "#{AttritionApi__Url}"
  otel:
    logging:
      enabled: false
  global:
    upstream:
      perTryTimeout: 60s
  routes:
    subdomains:
      - type: api
        product: driver
        app: insights
  deployment:
     podAnnotations:        
        instrumentation.opentelemetry.io/inject-dotnet: "otel/otel-instrumentation"
  istio:
    ingress:
      disableRewrite: true
    egress:
    
    # XPM
      - name: wildcard
        hosts:
          - '*.usxpress.com'
        ports: 
          - number: 443
            protocol: HTTPS
        resolution: NONE      
      
      - name: xpm
        hosts: 
          - '*.usxpress.com'
        ports:
          - number: 80
            protocol: HTTP
        resolution: NONE
      
      - name: seq-logging
        hosts:
          - 'usxseqlog.usxpress.com'
        ports:
          - number: 9997
            protocol: HTTP
        resolution: DNS

        #SQL SERVER
      - name: sql-psa-dev
        hosts:
          - 'USXSQLPSAQA.usxpress.com'
        ports:
          - number: 1433
            protocol: TCP
        
      - name: sql-psa-prod
        hosts:
          - 'USXSQLPSAPRD.usxpress.com'
        ports:
          - number: 1433
            protocol: TCP
      



