name: .NET Core Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Set the version of .NET you are using, e.g., '6.0', '7.0'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build the application
      run: dotnet build --configuration Release

    # Step 5: Run tests (if you have a test project)
    - name: Run tests
      run: dotnet test --configuration Release

    # Step 6: Publish the application (optional for deployment)
    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

    # Step 7: (Optional) Deploy to production or staging
    # Example of deploying to Azure App Service or Docker container
    # You can add deployment steps here based on your infrastructure.
