name: octo-push-dx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MASTER_BRANCH: master

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build Image and Push to Octo
    runs-on: [ubuntu-latest]

    permissions:
      id-token: write  # For OIDC if applicable
      contents: write  # For pushing changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Artifact 📦
        uses: variant-inc/actions-dotnet@v2
        with:
          dotnet-version: 8.0.x
          ecr_repository: usxpress/driver-hos-state-api

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Release 🛸
        uses: variant-inc/actions-octopus@v3
        with:
          deploy_yaml_dir: .octopus/deploy
