name: DX Build

on:
  push:
    branches:
      - "**"

jobs:
  dx-workfow:
    name: DX Workflow
    runs-on: [ubuntu-latest]

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Dotnet Things
        uses: variant-inc/actions-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          ecr_repository: 'usxpress/driver-hos-state-api'

        # This step sets up the project in Octopus Deploy
      - name: Octopus Action
        uses: variant-inc/actions-octopus@v3
