name: octo-push-dx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MASTER_BRANCH: master

on:
  push:
    branches:
      - "**"  # Will trigger on any branch push, adjust to limit to certain branches if needed.

jobs:
  build:
    name: Build Image and Push to Octo
    runs-on: [ubuntu-latest]

    permissions:
      id-token: write   # Required for OIDC
      contents: write   # Required to push changes to the repository (if needed)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build .NET Project
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./out

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/usxpress/driver-hos-state-api:latest .
        
      - name: Push Docker Image to ECR
        run: |
          docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/usxpress/driver-hos-state-api:latest

      - name: Deploy to Octopus
        uses: variant-inc/actions-octopus@v3
        with:
          octopus_api_key: ${{ secrets.OCTOPUS_API_KEY }}  # Set in GitHub secrets
          octopus_server: https://octopus.example.com  # Your Octopus server URL
          deploy_yaml_dir: .octopus/deploy
